name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Build typescript
        run: npm run build
      - name: Unit tests
        run: npm test
      - name: Integration tests
        run: npm run test:integration
